name: Docker - Development Build

#Run this action against any commit on main.
on:
  push:
    branches:
        - main
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache main image layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-main-cache
          key: ${{ runner.os }}-buildx-main-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-main-

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the latest commit hash and timestamp
        id: vars
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          COMMIT_TIMESTAMP=$(git show -s --format=%ct HEAD)
          PACKAGE_TIMESTAMP=$(date -u -d "@$COMMIT_TIMESTAMP" +'%Y%m%d%H%M%S')
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          echo "PACKAGE_TIMESTAMP=$PACKAGE_TIMESTAMP" >> $GITHUB_ENV
          
      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.dev
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          tags: ghcr.io/pkimetal/pkimetal-dev:${{ env.PACKAGE_TIMESTAMP }}
          labels: ghcr.io/pkimetal/pkimetal-dev:${{ env.PACKAGE_TIMESTAMP }}
          provenance: false

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
